recipients:
  - name: antony
    key: 43e74acaed93b89622d4169054341731192ae2e3382cd8df7f9be7dfa426900e
    kind: user
exclude:
  - .git
  - .github
  - node_modules
  - bin
  - coverage
  - .cloak.yaml
rules:
  - path_regex: .*\.secret$
    type: full
  - path_regex: .*\.ya?ml$
    type: yaml
    encrypted_keys:
      - password
      - secret
      - token
  - path_regex: .*\.json$
    type: json
    encrypted_keys:
      - password
      - secret
      - token
  - path_regex: .*\.env$
    type: env
    encrypted_keys:
      - PASSWORD
      - SECRET_KEY
