use clap::Parser;
use shadow_rs::shadow;

// This macro pulls in the constants generated by build.rs
shadow!(build);

/// A simple single-binary combining age and sops functionality
#[derive(Parser, Debug)]
#[command(name = "cloak")]
#[command(author = "Antony Lee")]
#[command(version = build::CLAP_LONG_VERSION)]
#[command(about = "Secret operations made simple", long_about = None)]
struct Cli {}

fn main() {
    // Parse arguments given to the CLI (e.g., --version, --help)
    let _cli = Cli::parse();

    println!("Welcome to cloak!");
}